image: golang:latest

stages:
  - test
  - build
  - release
  
.buildbase:
  stage: build
  needs:
    - test
  script:
    - make clean
    - make build -e GOOS=linux -e GOARCH=amd64 -e BUILD_TARGET=linux-amd64
    - make build -e GOOS=linux -e GOARCH=arm -e BUILD_TARGET=linux-arm
    - make build -e GOOS=linux -e GOARCH=arm64 -e BUILD_TARGET=linux-arm64
    - make build -e GOOS=linux -e GOARCH=arm -e GOARM=7 -e BUILD_TARGET=rpi3
    - make build -e GOOS=darwin -e GOARCH=amd64 -e BUILD_TARGET=macOS-amd64
    - make build -e GOOS=darwin -e GOARCH=arm64 -e BUILD_TARGET=macOS-applesilicon
    - make build -e GOOS=windows -e GOARCH=amd64 -e BUILD_TARGET=win-amd64

.builddpkgs:
  image: ubuntu:latest
  stage: build
  script:
    - apt update
    - apt-get install --yes make dh-make apt-utils dpkg-dev dpkg-sig ubuntu-dev-tools binutils-arm-linux-gnueabihf build-essential
    - make dpgk -e GOOS=linux -e GOARCH=amd64 -e BUILD_TARGET=linux-amd64
    - make dpgk -e GOOS=linux -e GOARCH=arm -e BUILD_TARGET=linux-arm
    - make dpgk -e GOOS=linux -e GOARCH=arm -e GOARM=7 -e BUILD_TARGET=rpi3

test:
  stage: test
  script:
    - make clean test

build:development:
  extends: .buildbase
  variables:
    APP_VERSION: dev
  artifacts:
    paths:
    - build
    expire_in: 1 week
  except:
    - main
    - master
    - tags

build:main:
  extends: .buildbase
  artifacts:
    paths:
    - build
    expire_in: 1 year
  only:
    - main
  except:
    - tags

build:tags:
  variables:
    APP_VERSION: $CI_COMMIT_TAG
  extends: .buildbase
  artifacts:
    paths:
    - build
    expire_in: never
  only:
    - tags
  
publish:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script: 
    - echo "Running a new release"
  dependencies: 
    - build:tags
  artifacts:
    paths:
    - build
  release:
    name: 'Release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
    description: See CHANGELOG.md
  only:
    - tags
