################################################################################
# Go-HomeKit-SystemD-Bridge config example
################################################################################
# This file is a configuration example 
# For more information, see: https://gitlab.com/koalalorenzo/go-hk-systemd-bridge

# Name of the service, Visible in Homekit
name: RaspberryPy

# Set the log level. If specified, the env variable LOG_LEVEL will be ingored
log_level: debug

# Pairing code used by HomeKit to pair
pairing_code: "10042002"

# Path of the Database to store files
db_path: "/usr/var/go-hk-systemd-bridge"

# How often should we check SystemD / cmds for status updates?
update_frequency: 30

# List of services to add to HomeKit as on/off switches
services: 
  - name: "nginx" # Use SystemD and default values

  - name: "HTTP Proxy" # Customize the HomeKit Switch name
    service_name: "nginx" # specify what is the systemd service name to check
  
  - name: "Media Server" # The name visible in HomeKit
    # You can customize on, off and periodic check commands. If these commands
    # return 0 then it means that the action is successfull.
    on_cmd: "docker start jellyfin" 
    off_cmd: "docker stop jellyfin"
    # If the period check command returns 0, the switch will be set to ON 
    check_cmd: "docker inspect --format='{{.State.Running}}' jellyfin"

  - name: "PiHole"
    # Or for example look into custom setup that will not be periodically
    # checked. Note that by default switches/services are "ON"
    on_cmd: "pihole enable"
    off_cmd: "pihole disable"
    check_cmd: "disabled"