name: "RaspberryPi"
db_path: "db"
update_frequency: 3
services: 
  - name: "jellyfin"
    oncmd: "return.sh 0"
    offcmd: "returh.sh 0"
    periodic_check_cmd: "return.sh 1"
    service_name: "pod-jellyfin"